### ISSUE TITLE
Korean model missing on Huggingface

### ISSUE THREAD

**Issue by jvamvas** [TurkuNLP/wikibert#1]
Thank you for providing this great resource!

It seems that the Korean model has not yet been uploaded to Huggingface (expected URL: https://huggingface.co/TurkuNLP/wikibert-base-ko-cased). Is this an oversight or is there a deeper reason for this?

**Comment by haamis** [comment]
Hi,

this seems like an honest mistake, I'll submit it once I get around to it. For now you can get the model from [http://dl.turkunlp.org/wikibert/wikibert-base-ko-cased/](http://dl.turkunlp.org/wikibert/wikibert-base-ko-cased/) (as linked in the README).

EDIT: Upload done, closing issue.
